<?php

use Illuminate\Database\Seeder;

class taiken_table_seeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
      $faker=Faker\Factory::create('ja_JP');
      $taikens=[
        [
          'field'=>'IT',
          'name'=>'Androidプログラミング体験'
        ],
        [
          'field'=>'IT',
          'name'=>'ネットワーク・セキュリティ体験'
        ],
        [
          'field'=>'IT',
          'name'=>'システムエンジニア体験'
        ],
        [
          'field'=>'IT',
          'name'=>'ネットワークエンジニア体験'
        ],
        [
          'field'=>'IT',
          'name'=>'Webプログラミング体験'
        ],
        [
          'field'=>'ビジネス',
          'name'=>'ビジネス体験'
        ],
        [
          'field'=>'ゲーム',
          'name'=>'ゲームプログラマー(モバイル)体験'
        ],
        [
          'field'=>'ゲーム',
          'name'=>'ゲームプログラマー(3Dアクション)体験'
        ],
        [
          'field'=>'ゲーム',
          'name'=>'ゲームプログラマー(オンライン)体験'
        ],
        [
          'field'=>'ゲーム',
          'name'=>'ゲームプランナー体験'
        ],
        [
          'field'=>'ゲーム',
          'name'=>'キャラクターデザイン体験'
        ],
        [
          'field'=>'ゲーム',
          'name'=>'ゲームCGデザイナー体験'
        ],
        [
          'field'=>'デザイン・Web・イラスト',
          'name'=>'デジタルイラスト体験'
        ],
        [
          'field'=>'デザイン・Web・イラスト',
          'name'=>'グラフィックデザイン体験'
        ],
        [
          'field'=>'デザイン・Web・イラスト',
          'name'=>'アナログイラスト体験'
        ],
        [
          'field'=>'デザイン・Web・イラスト',
          'name'=>'マンガイラスト体験'
        ],
        [
          'field'=>'デザイン・Web・イラスト',
          'name'=>'Webデザイン体験'
        ],
        [
          'field'=>'CG・映像・アニメーション系',
          'name'=>'3DCG体験'
        ],
        [
          'field'=>'CG・映像・アニメーション系',
          'name'=>'CG映像体験'
        ],
        [
          'field'=>'CG・映像・アニメーション系',
          'name'=>'画像合成体験'
        ],
        [
          'field'=>'学校説明会',
          'name'=>'学校説明会'
        ]
      ];
      foreach ($taikens as $taiken) {
        App\taiken::create($taiken);
      }
    }
}
